class Article
  # This represents a list of articles you have in your database
  ARTICLES = [
    {
      id: '1',
      title: 'Winter is Coming Time to Go Hiking',
      image: 'url(\'/images/take_a_hike.jpg\')',
      intro: 'Winter is approaching fast, so hurry up and take out your hiking equipment from the closet - we have some great tracks for you to try before it\'s too late.',
      author: 'Mister McManus',
      publish_date: '10 NOV 2015',
      likes: 1759,
      comments: 320,
      free_content: %(<p>You may have been expecting to find an article about winter hiking, which is a fairly sensible expectation. However, what you will find here, in fact, is a lot of good looking filler text. With the exception of this bit of text, of course, which was lovingly hand-crafted.</p>
                      <p>Yr asymmetrical cornhole, bushwick schlitz DIY literally helvetica. Deep v chillwave farm-to-table fingerstache helvetica, schlitz drinking vinegar. Taxidermy normcore locavore, four loko tofu listicle street art waistcoat trust fund jean shorts pabst wayfarers chillwave forage pop-up. Small batch fingerstache chartreuse cardigan, tattooed messenger bag cliche godard kinfolk gluten-free kombucha raw denim. Sustainable sartorial pinterest craft beer fap skateboard cardigan, listicle YOLO. Etsy bespoke leggings, photo booth crucifix freegan cray. Echo park cray scenester typewriter, offal godard you probably haven't heard of them neutra narwhal lomo forage art party.</p>
                      <p class="excerpt">This excerpt is supposed to make you feel engaged. Does it fill you with determination?</p>
                      <p>Scenester authentic cardigan hammock austin literally. Squid farm-to-table etsy mustache, hella butcher selfies authentic whatever meh. Retro wayfarers semiotics, thundercats cronut tofu fanny pack beard gentrify. Whatever squid humblebrag, chia viral tofu hella flannel fashion axe cliche cornhole. Yr 3 wolf moon mixtape quinoa banh mi green juice umami, squid deep v typewriter flannel drinking vinegar. Distillery skateboard pitchfork, VHS intelligentsia plaid cornhole forage kogi actually ennui shoreditch street art franzen wolf. Freegan synth occupy YOLO umami bitters.</p>),
      paid_content: %(
        <p>In the late 1970s, the development of Kevlar then Spectra flying lines and more controllable kites with improved efficiency contributed to practical kite traction. In 1978, Ian Day's "FlexiFoil" kite-powered Tornado catamaran exceeded 40 km/h.
        In October 1977 Gijsbertus Adrianus Panhuise (Netherlands) received the first patent[7] for KiteSurfing. The patent covers, specifically, a water sport using a floating board of a surf board type where a pilot standing up on it is pulled by a wind catching device of a parachute type tied to his harness on a trapeze type belt. Although this patent did not result in any commercial interest, Gijsbertus Adrianus Panhuise could be considered as the originator of KiteSurfing.
        Through the 1980s, there were occasionally successful attempts to combine kites with canoes, ice skates, snow skis,[8] water skis and roller skates.
        Throughout the 1970s and early 1980s, Dieter Strasilla from Germany developed parachute-skiing and later perfected a kiteskiing system using self made paragliders and a ball-socket swivel allowing the pilot to sail upwind and uphill but also to take off into the air at will.[9] Strasilla and his Swiss friend Andrea Kuhn used this invention also in combination with surfboards and snowboards, grasskies and selfmade buggies.[10] One of his patents describes in 1979 the first use of an inflatable kite design for kitesurfing.[11]
        Two brothers, Bruno Legaignoux and Dominique Legaignoux, from the Atlantic coast of France, developed kites for kitesurfing in the late 1970s and early 1980s and patented an inflatable kite design in November 1984, a design that has been used by companies to develop their own products.
        In 1990, practical kite buggying was pioneered by Peter Lynn at Argyle Park in Ashburton, New Zealand. Lynn coupled a three-wheeled buggy with a forerunner of the modern parafoil kite. Kite buggying proved to be very popular worldwide, with over 14,000 buggies sold up to 1999.
        The development of modern day kitesurfing by the Roeselers in the USA and the Legaignoux in France carried on in parallel to buggying. Bill Roeseler, a Boeing aerodynamicist, and his son Cory Roeseler patented the "KiteSki" system which consisted of water skis powered by a two line delta style kite controlled via a bar mounted combined winch/brake. The KiteSki was commercially available in 1994. The kite had a rudimentary water launch capability and could go upwind. In 1995, Cory Roeseler visited Peter Lynn at New Zealand's Lake Clearwater in the Ashburton Alpine Lakes area, demonstrating speed, balance and upwind angle on his 'ski'. In the late 1990s, Cory's ski evolved to a single board similar to a surfboard.[5]
        In 1996, Laird Hamilton and Manu Bertin were instrumental in demonstrating and popularising kitesurfing off the Hawaiian coast of Maui while in Florida Raphaël Baruch experimented riding windsurfing boards with various foil kites and changing the name of the sport from flysurfing to kitesurfing.
        In 1997, the Legaignoux brothers developed and sold the breakthrough "Wipika" kite design which had a structure of preformed inflatable tubes and a simple bridle system to the wingtips, both of which greatly assisted water re-launch. Bruno Legaignoux has continued to improve kite designs, including developing the bow kite design, which has been licensed to many kite manufacturers.
        In 1997, specialized kite boards were developed by Raphaël Salles and Laurent Ness. By the end of 1998 kitesurfing had become an extreme sport, distributed and taught through a handful group of shops and schools worldwide. The first competition was held on Maui in September 1998 and won by Flash Austin.[5]
        Starting in 1999, kitesurfing became a mainstream sport with the entry of key windsurfing manufacturers namely Naish and Neil Pryde. Single direction boards derived from windsurfing and surfing designs became the dominant form of kiteboard. From 2001 onwards, twin-tip bi-directional boards became more popular for most flat water riders, with directional boards still in use for surf conditions.
        In May 2012, the course racing style of kitesurfing was announced as a sport for the 2016 Rio Olympics,[12] replacing windsurfing. However, after a vote by the General Assembly of ISAF in November 2012 (in Dun Laoghaire, Ireland) the RSX windsurfer was reinstated for both Men and Women this was an unprecedented decision when the constituent members of ISAF overthrew a decision made by the ISAF Council [13]Kitesurfing remains therefore a non-Olympic sport until 2020 at the earliest. The ISAF mid-year meeting of May 2013 proposed seeking an eleventh medal to include kitesurfing in 2020 [14] at the same time there was a commitment made to retain the existing other 10 classes as they are for 2020 and even 2024 including the RSX windsurfer for men and women.</p> )
    },
    {
      id: '2',
      title: 'It\'s Not a Lake, It\'s an Ocean',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Boracay_kitesurfing.jpg/330px-Boracay_kitesurfing.jpg',
      intro: 'Kiteboarding is a surface water sport combining aspects of wakeboarding, windsurfing, surfing, paragliding, and gymnastics into one extreme sport. A kiteboarder harnesses the power of the wind with a large controllable power kite to be propelled across the water on a kiteboard similar to a wakeboard or a small surfboard, with or without footstraps or bindings.Kitesurfing is a style of kiteboarding specific to wave riding, which utilizes standard surfboards or boards shaped specifically for the purpose.There are different styles of kiteboarding, including freestyle, freeride, downwinders, speed, course racing, wakestyle, jumping and kitesurfing in the waves.[1] In 2012, the number of kitesurfers was estimated by the ISAF and IKA at 1.5 million persons worldwide [2] (pending review). The global market for kite gear sales is worth US$321 million.[3]',
      author: 'Alan Wake',
      publish_date: '14 MAY 2010',
      likes: 837,
      comments: 666,
      free_content: %(<p>In the 1800s, George Pocock used kites of increased size to propel carts on land and ships on the water, using a four-line control system—the same system in common use today. Both carts and boats were able to turn and sail upwind. The kites could be flown for sustained periods.[4] The intention was to establish kitepower as an alternative to horsepower, partly to avoid the hated "horse tax" that was levied at that time.[5] In 1903, aviation pioneer Samuel Cody developed "man-lifting kites" and succeeded in crossing the English Channel in a small collapsible canvas boat powered by a kite[6]</p>),
      paid_content: %(
        <p>In the late 1970s, the development of Kevlar then Spectra flying lines and more controllable kites with improved efficiency contributed to practical kite traction. In 1978, Ian Day's "FlexiFoil" kite-powered Tornado catamaran exceeded 40 km/h.
        In October 1977 Gijsbertus Adrianus Panhuise (Netherlands) received the first patent[7] for KiteSurfing. The patent covers, specifically, a water sport using a floating board of a surf board type where a pilot standing up on it is pulled by a wind catching device of a parachute type tied to his harness on a trapeze type belt. Although this patent did not result in any commercial interest, Gijsbertus Adrianus Panhuise could be considered as the originator of KiteSurfing.
        Through the 1980s, there were occasionally successful attempts to combine kites with canoes, ice skates, snow skis,[8] water skis and roller skates.
        Throughout the 1970s and early 1980s, Dieter Strasilla from Germany developed parachute-skiing and later perfected a kiteskiing system using self made paragliders and a ball-socket swivel allowing the pilot to sail upwind and uphill but also to take off into the air at will.[9] Strasilla and his Swiss friend Andrea Kuhn used this invention also in combination with surfboards and snowboards, grasskies and selfmade buggies.[10] One of his patents describes in 1979 the first use of an inflatable kite design for kitesurfing.[11]
        Two brothers, Bruno Legaignoux and Dominique Legaignoux, from the Atlantic coast of France, developed kites for kitesurfing in the late 1970s and early 1980s and patented an inflatable kite design in November 1984, a design that has been used by companies to develop their own products.
        In 1990, practical kite buggying was pioneered by Peter Lynn at Argyle Park in Ashburton, New Zealand. Lynn coupled a three-wheeled buggy with a forerunner of the modern parafoil kite. Kite buggying proved to be very popular worldwide, with over 14,000 buggies sold up to 1999.
        The development of modern day kitesurfing by the Roeselers in the USA and the Legaignoux in France carried on in parallel to buggying. Bill Roeseler, a Boeing aerodynamicist, and his son Cory Roeseler patented the "KiteSki" system which consisted of water skis powered by a two line delta style kite controlled via a bar mounted combined winch/brake. The KiteSki was commercially available in 1994. The kite had a rudimentary water launch capability and could go upwind. In 1995, Cory Roeseler visited Peter Lynn at New Zealand's Lake Clearwater in the Ashburton Alpine Lakes area, demonstrating speed, balance and upwind angle on his 'ski'. In the late 1990s, Cory's ski evolved to a single board similar to a surfboard.[5]
        In 1996, Laird Hamilton and Manu Bertin were instrumental in demonstrating and popularising kitesurfing off the Hawaiian coast of Maui while in Florida Raphaël Baruch experimented riding windsurfing boards with various foil kites and changing the name of the sport from flysurfing to kitesurfing.
        In 1997, the Legaignoux brothers developed and sold the breakthrough "Wipika" kite design which had a structure of preformed inflatable tubes and a simple bridle system to the wingtips, both of which greatly assisted water re-launch. Bruno Legaignoux has continued to improve kite designs, including developing the bow kite design, which has been licensed to many kite manufacturers.
        In 1997, specialized kite boards were developed by Raphaël Salles and Laurent Ness. By the end of 1998 kitesurfing had become an extreme sport, distributed and taught through a handful group of shops and schools worldwide. The first competition was held on Maui in September 1998 and won by Flash Austin.[5]
        Starting in 1999, kitesurfing became a mainstream sport with the entry of key windsurfing manufacturers namely Naish and Neil Pryde. Single direction boards derived from windsurfing and surfing designs became the dominant form of kiteboard. From 2001 onwards, twin-tip bi-directional boards became more popular for most flat water riders, with directional boards still in use for surf conditions.
        In May 2012, the course racing style of kitesurfing was announced as a sport for the 2016 Rio Olympics,[12] replacing windsurfing. However, after a vote by the General Assembly of ISAF in November 2012 (in Dun Laoghaire, Ireland) the RSX windsurfer was reinstated for both Men and Women this was an unprecedented decision when the constituent members of ISAF overthrew a decision made by the ISAF Council [13]Kitesurfing remains therefore a non-Olympic sport until 2020 at the earliest. The ISAF mid-year meeting of May 2013 proposed seeking an eleventh medal to include kitesurfing in 2020 [14] at the same time there was a commitment made to retain the existing other 10 classes as they are for 2020 and even 2024 including the RSX windsurfer for men and women.</p> )
    },
    {
      id: '3',
      title: 'Metroids and You',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Boracay_kitesurfing.jpg/330px-Boracay_kitesurfing.jpg',
      intro: 'Kiteboarding is a surface water sport combining aspects of wakeboarding, windsurfing, surfing, paragliding, and gymnastics into one extreme sport. A kiteboarder harnesses the power of the wind with a large controllable power kite to be propelled across the water on a kiteboard similar to a wakeboard or a small surfboard, with or without footstraps or bindings.Kitesurfing is a style of kiteboarding specific to wave riding, which utilizes standard surfboards or boards shaped specifically for the purpose.There are different styles of kiteboarding, including freestyle, freeride, downwinders, speed, course racing, wakestyle, jumping and kitesurfing in the waves.[1] In 2012, the number of kitesurfers was estimated by the ISAF and IKA at 1.5 million persons worldwide [2] (pending review). The global market for kite gear sales is worth US$321 million.[3]',
      author: 'Samus Aran',
      publish_date: '6 NOV 2015',
      likes: 234,
      comments: 94,
      free_content: %(<p>In the 1800s, George Pocock used kites of increased size to propel carts on land and ships on the water, using a four-line control system—the same system in common use today. Both carts and boats were able to turn and sail upwind. The kites could be flown for sustained periods.[4] The intention was to establish kitepower as an alternative to horsepower, partly to avoid the hated "horse tax" that was levied at that time.[5] In 1903, aviation pioneer Samuel Cody developed "man-lifting kites" and succeeded in crossing the English Channel in a small collapsible canvas boat powered by a kite[6]</p>),
      paid_content: %(
        <p>In the late 1970s, the development of Kevlar then Spectra flying lines and more controllable kites with improved efficiency contributed to practical kite traction. In 1978, Ian Day's "FlexiFoil" kite-powered Tornado catamaran exceeded 40 km/h.
        In October 1977 Gijsbertus Adrianus Panhuise (Netherlands) received the first patent[7] for KiteSurfing. The patent covers, specifically, a water sport using a floating board of a surf board type where a pilot standing up on it is pulled by a wind catching device of a parachute type tied to his harness on a trapeze type belt. Although this patent did not result in any commercial interest, Gijsbertus Adrianus Panhuise could be considered as the originator of KiteSurfing.
        Through the 1980s, there were occasionally successful attempts to combine kites with canoes, ice skates, snow skis,[8] water skis and roller skates.
        Throughout the 1970s and early 1980s, Dieter Strasilla from Germany developed parachute-skiing and later perfected a kiteskiing system using self made paragliders and a ball-socket swivel allowing the pilot to sail upwind and uphill but also to take off into the air at will.[9] Strasilla and his Swiss friend Andrea Kuhn used this invention also in combination with surfboards and snowboards, grasskies and selfmade buggies.[10] One of his patents describes in 1979 the first use of an inflatable kite design for kitesurfing.[11]
        Two brothers, Bruno Legaignoux and Dominique Legaignoux, from the Atlantic coast of France, developed kites for kitesurfing in the late 1970s and early 1980s and patented an inflatable kite design in November 1984, a design that has been used by companies to develop their own products.
        In 1990, practical kite buggying was pioneered by Peter Lynn at Argyle Park in Ashburton, New Zealand. Lynn coupled a three-wheeled buggy with a forerunner of the modern parafoil kite. Kite buggying proved to be very popular worldwide, with over 14,000 buggies sold up to 1999.
        The development of modern day kitesurfing by the Roeselers in the USA and the Legaignoux in France carried on in parallel to buggying. Bill Roeseler, a Boeing aerodynamicist, and his son Cory Roeseler patented the "KiteSki" system which consisted of water skis powered by a two line delta style kite controlled via a bar mounted combined winch/brake. The KiteSki was commercially available in 1994. The kite had a rudimentary water launch capability and could go upwind. In 1995, Cory Roeseler visited Peter Lynn at New Zealand's Lake Clearwater in the Ashburton Alpine Lakes area, demonstrating speed, balance and upwind angle on his 'ski'. In the late 1990s, Cory's ski evolved to a single board similar to a surfboard.[5]
        In 1996, Laird Hamilton and Manu Bertin were instrumental in demonstrating and popularising kitesurfing off the Hawaiian coast of Maui while in Florida Raphaël Baruch experimented riding windsurfing boards with various foil kites and changing the name of the sport from flysurfing to kitesurfing.
        In 1997, the Legaignoux brothers developed and sold the breakthrough "Wipika" kite design which had a structure of preformed inflatable tubes and a simple bridle system to the wingtips, both of which greatly assisted water re-launch. Bruno Legaignoux has continued to improve kite designs, including developing the bow kite design, which has been licensed to many kite manufacturers.
        In 1997, specialized kite boards were developed by Raphaël Salles and Laurent Ness. By the end of 1998 kitesurfing had become an extreme sport, distributed and taught through a handful group of shops and schools worldwide. The first competition was held on Maui in September 1998 and won by Flash Austin.[5]
        Starting in 1999, kitesurfing became a mainstream sport with the entry of key windsurfing manufacturers namely Naish and Neil Pryde. Single direction boards derived from windsurfing and surfing designs became the dominant form of kiteboard. From 2001 onwards, twin-tip bi-directional boards became more popular for most flat water riders, with directional boards still in use for surf conditions.
        In May 2012, the course racing style of kitesurfing was announced as a sport for the 2016 Rio Olympics,[12] replacing windsurfing. However, after a vote by the General Assembly of ISAF in November 2012 (in Dun Laoghaire, Ireland) the RSX windsurfer was reinstated for both Men and Women this was an unprecedented decision when the constituent members of ISAF overthrew a decision made by the ISAF Council [13]Kitesurfing remains therefore a non-Olympic sport until 2020 at the earliest. The ISAF mid-year meeting of May 2013 proposed seeking an eleventh medal to include kitesurfing in 2020 [14] at the same time there was a commitment made to retain the existing other 10 classes as they are for 2020 and even 2024 including the RSX windsurfer for men and women.</p> )
    },
    {
      id: '4',
      title: 'Your Neighbour - an Excellent Source of Nutrition',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Boracay_kitesurfing.jpg/330px-Boracay_kitesurfing.jpg',
      intro: 'Kiteboarding is a surface water sport combining aspects of wakeboarding, windsurfing, surfing, paragliding, and gymnastics into one extreme sport. A kiteboarder harnesses the power of the wind with a large controllable power kite to be propelled across the water on a kiteboard similar to a wakeboard or a small surfboard, with or without footstraps or bindings.Kitesurfing is a style of kiteboarding specific to wave riding, which utilizes standard surfboards or boards shaped specifically for the purpose.There are different styles of kiteboarding, including freestyle, freeride, downwinders, speed, course racing, wakestyle, jumping and kitesurfing in the waves.[1] In 2012, the number of kitesurfers was estimated by the ISAF and IKA at 1.5 million persons worldwide [2] (pending review). The global market for kite gear sales is worth US$321 million.[3]',
      author: 'Hannibal Lecter',
      publish_date: '6 NOV 2015',
      likes: 234,
      comments: 94,
      free_content: %(<p>In the 1800s, George Pocock used kites of increased size to propel carts on land and ships on the water, using a four-line control system—the same system in common use today. Both carts and boats were able to turn and sail upwind. The kites could be flown for sustained periods.[4] The intention was to establish kitepower as an alternative to horsepower, partly to avoid the hated "horse tax" that was levied at that time.[5] In 1903, aviation pioneer Samuel Cody developed "man-lifting kites" and succeeded in crossing the English Channel in a small collapsible canvas boat powered by a kite[6]</p>),
      paid_content: %(
        <p>In the late 1970s, the development of Kevlar then Spectra flying lines and more controllable kites with improved efficiency contributed to practical kite traction. In 1978, Ian Day's "FlexiFoil" kite-powered Tornado catamaran exceeded 40 km/h.
        In October 1977 Gijsbertus Adrianus Panhuise (Netherlands) received the first patent[7] for KiteSurfing. The patent covers, specifically, a water sport using a floating board of a surf board type where a pilot standing up on it is pulled by a wind catching device of a parachute type tied to his harness on a trapeze type belt. Although this patent did not result in any commercial interest, Gijsbertus Adrianus Panhuise could be considered as the originator of KiteSurfing.
        Through the 1980s, there were occasionally successful attempts to combine kites with canoes, ice skates, snow skis,[8] water skis and roller skates.
        Throughout the 1970s and early 1980s, Dieter Strasilla from Germany developed parachute-skiing and later perfected a kiteskiing system using self made paragliders and a ball-socket swivel allowing the pilot to sail upwind and uphill but also to take off into the air at will.[9] Strasilla and his Swiss friend Andrea Kuhn used this invention also in combination with surfboards and snowboards, grasskies and selfmade buggies.[10] One of his patents describes in 1979 the first use of an inflatable kite design for kitesurfing.[11]
        Two brothers, Bruno Legaignoux and Dominique Legaignoux, from the Atlantic coast of France, developed kites for kitesurfing in the late 1970s and early 1980s and patented an inflatable kite design in November 1984, a design that has been used by companies to develop their own products.
        In 1990, practical kite buggying was pioneered by Peter Lynn at Argyle Park in Ashburton, New Zealand. Lynn coupled a three-wheeled buggy with a forerunner of the modern parafoil kite. Kite buggying proved to be very popular worldwide, with over 14,000 buggies sold up to 1999.
        The development of modern day kitesurfing by the Roeselers in the USA and the Legaignoux in France carried on in parallel to buggying. Bill Roeseler, a Boeing aerodynamicist, and his son Cory Roeseler patented the "KiteSki" system which consisted of water skis powered by a two line delta style kite controlled via a bar mounted combined winch/brake. The KiteSki was commercially available in 1994. The kite had a rudimentary water launch capability and could go upwind. In 1995, Cory Roeseler visited Peter Lynn at New Zealand's Lake Clearwater in the Ashburton Alpine Lakes area, demonstrating speed, balance and upwind angle on his 'ski'. In the late 1990s, Cory's ski evolved to a single board similar to a surfboard.[5]
        In 1996, Laird Hamilton and Manu Bertin were instrumental in demonstrating and popularising kitesurfing off the Hawaiian coast of Maui while in Florida Raphaël Baruch experimented riding windsurfing boards with various foil kites and changing the name of the sport from flysurfing to kitesurfing.
        In 1997, the Legaignoux brothers developed and sold the breakthrough "Wipika" kite design which had a structure of preformed inflatable tubes and a simple bridle system to the wingtips, both of which greatly assisted water re-launch. Bruno Legaignoux has continued to improve kite designs, including developing the bow kite design, which has been licensed to many kite manufacturers.
        In 1997, specialized kite boards were developed by Raphaël Salles and Laurent Ness. By the end of 1998 kitesurfing had become an extreme sport, distributed and taught through a handful group of shops and schools worldwide. The first competition was held on Maui in September 1998 and won by Flash Austin.[5]
        Starting in 1999, kitesurfing became a mainstream sport with the entry of key windsurfing manufacturers namely Naish and Neil Pryde. Single direction boards derived from windsurfing and surfing designs became the dominant form of kiteboard. From 2001 onwards, twin-tip bi-directional boards became more popular for most flat water riders, with directional boards still in use for surf conditions.
        In May 2012, the course racing style of kitesurfing was announced as a sport for the 2016 Rio Olympics,[12] replacing windsurfing. However, after a vote by the General Assembly of ISAF in November 2012 (in Dun Laoghaire, Ireland) the RSX windsurfer was reinstated for both Men and Women this was an unprecedented decision when the constituent members of ISAF overthrew a decision made by the ISAF Council [13]Kitesurfing remains therefore a non-Olympic sport until 2020 at the earliest. The ISAF mid-year meeting of May 2013 proposed seeking an eleventh medal to include kitesurfing in 2020 [14] at the same time there was a commitment made to retain the existing other 10 classes as they are for 2020 and even 2024 including the RSX windsurfer for men and women.</p> )
    },
    {
      id: '5',
      title: 'Having Your Cake and Eating It - a Guide',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Boracay_kitesurfing.jpg/330px-Boracay_kitesurfing.jpg',
      intro: 'Kiteboarding is a surface water sport combining aspects of wakeboarding, windsurfing, surfing, paragliding, and gymnastics into one extreme sport. A kiteboarder harnesses the power of the wind with a large controllable power kite to be propelled across the water on a kiteboard similar to a wakeboard or a small surfboard, with or without footstraps or bindings.Kitesurfing is a style of kiteboarding specific to wave riding, which utilizes standard surfboards or boards shaped specifically for the purpose.There are different styles of kiteboarding, including freestyle, freeride, downwinders, speed, course racing, wakestyle, jumping and kitesurfing in the waves.[1] In 2012, the number of kitesurfers was estimated by the ISAF and IKA at 1.5 million persons worldwide [2] (pending review). The global market for kite gear sales is worth US$321 million.[3]',
      author: 'Dude Duderson',
      publish_date: '6 NOV 2015',
      likes: 234,
      comments: 94,
      free_content: %(<p>In the 1800s, George Pocock used kites of increased size to propel carts on land and ships on the water, using a four-line control system—the same system in common use today. Both carts and boats were able to turn and sail upwind. The kites could be flown for sustained periods.[4] The intention was to establish kitepower as an alternative to horsepower, partly to avoid the hated "horse tax" that was levied at that time.[5] In 1903, aviation pioneer Samuel Cody developed "man-lifting kites" and succeeded in crossing the English Channel in a small collapsible canvas boat powered by a kite[6]</p>),
      paid_content: %(
        <p>In the late 1970s, the development of Kevlar then Spectra flying lines and more controllable kites with improved efficiency contributed to practical kite traction. In 1978, Ian Day's "FlexiFoil" kite-powered Tornado catamaran exceeded 40 km/h.
        In October 1977 Gijsbertus Adrianus Panhuise (Netherlands) received the first patent[7] for KiteSurfing. The patent covers, specifically, a water sport using a floating board of a surf board type where a pilot standing up on it is pulled by a wind catching device of a parachute type tied to his harness on a trapeze type belt. Although this patent did not result in any commercial interest, Gijsbertus Adrianus Panhuise could be considered as the originator of KiteSurfing.
        Through the 1980s, there were occasionally successful attempts to combine kites with canoes, ice skates, snow skis,[8] water skis and roller skates.
        Throughout the 1970s and early 1980s, Dieter Strasilla from Germany developed parachute-skiing and later perfected a kiteskiing system using self made paragliders and a ball-socket swivel allowing the pilot to sail upwind and uphill but also to take off into the air at will.[9] Strasilla and his Swiss friend Andrea Kuhn used this invention also in combination with surfboards and snowboards, grasskies and selfmade buggies.[10] One of his patents describes in 1979 the first use of an inflatable kite design for kitesurfing.[11]
        Two brothers, Bruno Legaignoux and Dominique Legaignoux, from the Atlantic coast of France, developed kites for kitesurfing in the late 1970s and early 1980s and patented an inflatable kite design in November 1984, a design that has been used by companies to develop their own products.
        In 1990, practical kite buggying was pioneered by Peter Lynn at Argyle Park in Ashburton, New Zealand. Lynn coupled a three-wheeled buggy with a forerunner of the modern parafoil kite. Kite buggying proved to be very popular worldwide, with over 14,000 buggies sold up to 1999.
        The development of modern day kitesurfing by the Roeselers in the USA and the Legaignoux in France carried on in parallel to buggying. Bill Roeseler, a Boeing aerodynamicist, and his son Cory Roeseler patented the "KiteSki" system which consisted of water skis powered by a two line delta style kite controlled via a bar mounted combined winch/brake. The KiteSki was commercially available in 1994. The kite had a rudimentary water launch capability and could go upwind. In 1995, Cory Roeseler visited Peter Lynn at New Zealand's Lake Clearwater in the Ashburton Alpine Lakes area, demonstrating speed, balance and upwind angle on his 'ski'. In the late 1990s, Cory's ski evolved to a single board similar to a surfboard.[5]
        In 1996, Laird Hamilton and Manu Bertin were instrumental in demonstrating and popularising kitesurfing off the Hawaiian coast of Maui while in Florida Raphaël Baruch experimented riding windsurfing boards with various foil kites and changing the name of the sport from flysurfing to kitesurfing.
        In 1997, the Legaignoux brothers developed and sold the breakthrough "Wipika" kite design which had a structure of preformed inflatable tubes and a simple bridle system to the wingtips, both of which greatly assisted water re-launch. Bruno Legaignoux has continued to improve kite designs, including developing the bow kite design, which has been licensed to many kite manufacturers.
        In 1997, specialized kite boards were developed by Raphaël Salles and Laurent Ness. By the end of 1998 kitesurfing had become an extreme sport, distributed and taught through a handful group of shops and schools worldwide. The first competition was held on Maui in September 1998 and won by Flash Austin.[5]
        Starting in 1999, kitesurfing became a mainstream sport with the entry of key windsurfing manufacturers namely Naish and Neil Pryde. Single direction boards derived from windsurfing and surfing designs became the dominant form of kiteboard. From 2001 onwards, twin-tip bi-directional boards became more popular for most flat water riders, with directional boards still in use for surf conditions.
        In May 2012, the course racing style of kitesurfing was announced as a sport for the 2016 Rio Olympics,[12] replacing windsurfing. However, after a vote by the General Assembly of ISAF in November 2012 (in Dun Laoghaire, Ireland) the RSX windsurfer was reinstated for both Men and Women this was an unprecedented decision when the constituent members of ISAF overthrew a decision made by the ISAF Council [13]Kitesurfing remains therefore a non-Olympic sport until 2020 at the earliest. The ISAF mid-year meeting of May 2013 proposed seeking an eleventh medal to include kitesurfing in 2020 [14] at the same time there was a commitment made to retain the existing other 10 classes as they are for 2020 and even 2024 including the RSX windsurfer for men and women.</p> )
    }
  ]

  def self.all
    ARTICLES.map{|article| Article.new(article) }
  end

  def self.find id
    all.find{ |article| article.id == id }
  end

  attr_reader :id, :title, :image, :intro, :author, :publish_date, :likes, :comments, :free_content, :paid_content

  def initialize(id:, title:, image:, intro:, author:, publish_date:, likes:, comments:, free_content:, paid_content:)
    @id = id
    @title = title
    @image = image
    @intro = intro
    @author = author
    @publish_date = publish_date
    @likes = likes
    @comments = comments
    @free_content = free_content
    @paid_content = paid_content
  end

  def related
    Article.all.reject{|a| a.id == id}.shuffle.take(3)
  end
end
