class Article
  # This represents a list of articles you have in your database
  ARTICLES = [
    {
      id: '1',
      title: 'Kitesurfing (Purchase only)',
      tagline: 'Kiteboarding is a surface water sport combining aspects of wakeboarding, windsurfing, surfing, paragliding, and gymnastics into one extreme sport',
      image: 'http://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Boracay_kitesurfing.jpg/330px-Boracay_kitesurfing.jpg',
      summary: 'Kiteboarding is a surface water sport combining aspects of wakeboarding, windsurfing, surfing, paragliding, and gymnastics into one extreme sport. A kiteboarder harnesses the power of the wind with a large controllable power kite to be propelled across the water on a kiteboard similar to a wakeboard or a small surfboard, with or without footstraps or bindings.Kitesurfing is a style of kiteboarding specific to wave riding, which utilizes standard surfboards or boards shaped specifically for the purpose.There are different styles of kiteboarding, including freestyle, freeride, downwinders, speed, course racing, wakestyle, jumping and kitesurfing in the waves.[1] In 2012, the number of kitesurfers was estimated by the ISAF and IKA at 1.5 million persons worldwide [2] (pending review). The global market for kite gear sales is worth US$321 million.[3]',
      free_content: %(<p>In the 1800s, George Pocock used kites of increased size to propel carts on land and ships on the water, using a four-line control system—the same system in common use today. Both carts and boats were able to turn and sail upwind. The kites could be flown for sustained periods.[4] The intention was to establish kitepower as an alternative to horsepower, partly to avoid the hated "horse tax" that was levied at that time.[5] In 1903, aviation pioneer Samuel Cody developed "man-lifting kites" and succeeded in crossing the English Channel in a small collapsible canvas boat powered by a kite[6]
        In the late 1970s, the development of Kevlar then Spectra flying lines and more controllable kites with improved efficiency contributed to practical kite traction. In 1978, Ian Day's "FlexiFoil" kite-powered Tornado catamaran exceeded 40 km/h.
        In October 1977 Gijsbertus Adrianus Panhuise (Netherlands) received the first patent[7] for KiteSurfing. The patent covers, specifically, a water sport using a floating board of a surf board type where a pilot standing up on it is pulled by a wind catching device of a parachute type tied to his harness on a trapeze type belt. Although this patent did not result in any commercial interest, Gijsbertus Adrianus Panhuise could be considered as the originator of KiteSurfing.
        Through the 1980s, there were occasionally successful attempts to combine kites with canoes, ice skates, snow skis,[8] water skis and roller skates.
        Throughout the 1970s and early 1980s, Dieter Strasilla from Germany developed parachute-skiing and later perfected a kiteskiing system using self made paragliders and a ball-socket swivel allowing the pilot to sail upwind and uphill but also to take off into the air at will.[9] Strasilla and his Swiss friend Andrea Kuhn used this invention also in combination with surfboards and snowboards, grasskies and selfmade buggies.[10] One of his patents describes in 1979 the first use of an inflatable kite design for kitesurfing.[11]</p>),
      paid_content: %(
        <p>Two brothers, Bruno Legaignoux and Dominique Legaignoux, from the Atlantic coast of France, developed kites for kitesurfing in the late 1970s and early 1980s and patented an inflatable kite design in November 1984, a design that has been used by companies to develop their own products.
        In 1990, practical kite buggying was pioneered by Peter Lynn at Argyle Park in Ashburton, New Zealand. Lynn coupled a three-wheeled buggy with a forerunner of the modern parafoil kite. Kite buggying proved to be very popular worldwide, with over 14,000 buggies sold up to 1999.
        The development of modern day kitesurfing by the Roeselers in the USA and the Legaignoux in France carried on in parallel to buggying. Bill Roeseler, a Boeing aerodynamicist, and his son Cory Roeseler patented the "KiteSki" system which consisted of water skis powered by a two line delta style kite controlled via a bar mounted combined winch/brake. The KiteSki was commercially available in 1994. The kite had a rudimentary water launch capability and could go upwind. In 1995, Cory Roeseler visited Peter Lynn at New Zealand's Lake Clearwater in the Ashburton Alpine Lakes area, demonstrating speed, balance and upwind angle on his 'ski'. In the late 1990s, Cory's ski evolved to a single board similar to a surfboard.[5]
        In 1996, Laird Hamilton and Manu Bertin were instrumental in demonstrating and popularising kitesurfing off the Hawaiian coast of Maui while in Florida Raphaël Baruch experimented riding windsurfing boards with various foil kites and changing the name of the sport from flysurfing to kitesurfing.
        In 1997, the Legaignoux brothers developed and sold the breakthrough "Wipika" kite design which had a structure of preformed inflatable tubes and a simple bridle system to the wingtips, both of which greatly assisted water re-launch. Bruno Legaignoux has continued to improve kite designs, including developing the bow kite design, which has been licensed to many kite manufacturers.
        In 1997, specialized kite boards were developed by Raphaël Salles and Laurent Ness. By the end of 1998 kitesurfing had become an extreme sport, distributed and taught through a handful group of shops and schools worldwide. The first competition was held on Maui in September 1998 and won by Flash Austin.[5]
        Starting in 1999, kitesurfing became a mainstream sport with the entry of key windsurfing manufacturers namely Naish and Neil Pryde. Single direction boards derived from windsurfing and surfing designs became the dominant form of kiteboard. From 2001 onwards, twin-tip bi-directional boards became more popular for most flat water riders, with directional boards still in use for surf conditions.
        In May 2012, the course racing style of kitesurfing was announced as a sport for the 2016 Rio Olympics,[12] replacing windsurfing. However, after a vote by the General Assembly of ISAF in November 2012 (in Dun Laoghaire, Ireland) the RSX windsurfer was reinstated for both Men and Women this was an unprecedented decision when the constituent members of ISAF overthrew a decision made by the ISAF Council [13]Kitesurfing remains therefore a non-Olympic sport until 2020 at the earliest. The ISAF mid-year meeting of May 2013 proposed seeking an eleventh medal to include kitesurfing in 2020 [14] at the same time there was a commitment made to retain the existing other 10 classes as they are for 2020 and even 2024 including the RSX windsurfer for men and women.</p> )
    },
    {
      id: '2',
      title: 'Gutenberg creates an innovative printing system',
      tagline: 'The new system promises a revolution on how people consume content',
      image: 'http://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Metal_movable_type.jpg/1920px-Metal_movable_type.jpg',
      summary: "The printing press was invented in the Holy Roman Empire by Johannes Gutenberg, around 1440. Gutenberg, a goldsmith by profession, devised a hand mould to create metal movable type, and adapted screw presses and other existing technologies, to create a printing system.",
      free_content: "<p>The printing press was invented in the Holy Roman Empire by Johannes Gutenberg, around 1440. Gutenberg, a goldsmith by profession, devised a hand mould to create metal movable type, and adapted screw presses and other existing technologies, to create a printing system. The mechanization of bookmaking led to the first mass production of books in Europe. A single Renaissance printing press could produce 3,600 pages per workday, compared to about 2,000 by typographic block-printing prevalent in East Asia, and a few by hand-copying. Books of bestselling authors like Luther or Erasmus were sold by the hundreds of thousands in their lifetime.</p>",
      paid_content: %(
        <img style="width: 44%; float: left; margin-right: 20px;" src="http://upload.wikimedia.org/wikipedia/commons/f/f8/Printer_in_1568-ce.png" />
        <p>Within several decades, the printing press spread to over two hundred cities in a dozen European countries. By 1500, printing presses in operation throughout Western Europe had produced more than twenty million volumes. In the 16th century, with presses spreading further afield, their output rose to an estimated 150 to 200 million copies. The operation of a printing press became synonymous with the enterprise of printing, and lent its name to a new branch of media, the press. In 1620, the English philosopher Francis Bacon wrote of printing as one of three inventions that had changed the world.</p>
        <p>In the 19th century, the replacement of the hand-operated Gutenberg-style press by steam-powered rotary presses allowed printing on an industrial scale, while Western-style printing was adopted all over the world, becoming practically the sole medium for modern bulk printing, today typically using offset printing techniques.</p>
        <blockquote>The concept of movable type was not new in the 15th century; movable type printing had been invented in China during the Song dynasty</blockquote>
        <p>The rapid economic and socio-cultural development of late medieval society in Europe created favorable intellectual and technological conditions for Gutenberg's invention: the entrepreneurial spirit of emerging capitalism increasingly made its impact on medieval modes of production, fostering economic thinking and improving the efficiency of traditional work-processes. The sharp rise of medieval learning and literacy amongst the middle class led to an increased demand for books which the time-consuming hand-copying method fell far short of accommodating.
        <p>At the same time, a number of medieval products and technological processes had reached a level of maturity which allowed their potential use for printing purposes. Gutenberg took up these far-flung strands, combined them into one complete and functioning system, and perfected the printing process through all its stages by adding a number of inventions and innovations of his own.</p>
        <p>The screw press which allowed direct pressure to be applied on flat-plane was already of great antiquity in Gutenberg's time and was used for a wide range of tasks. Introduced in the 1st century AD by the Romans, it was commonly employed in agricultural production for pressing wine grapes and (olive) oil fruit, both of which formed an integral part of the mediterranean and medieval diet. The device was also used from very early on in urban contexts as a cloth press for printing patterns. Gutenberg may have also been inspired by the paper presses which had spread through the German lands since the late 14th century and which worked on the same mechanical principles.</p>
        <p>Gutenberg adopted the basic design, thereby mechanizing the printing process. Printing, however, put a demand on the machine quite different from pressing. Gutenberg adapted the construction so that the pressing power exerted by the platen on the paper was now applied both evenly and with the required sudden elasticity. To speed up the printing process, he introduced a movable undertable with a plane surface on which the sheets could be swiftly changed.</p>
        <p>The concept of movable type was not new in the 15th century; movable type printing had been invented in China during the Song dynasty, and was later used in Korea during the Goryeo Dynasty, where metal movable-type printing technology was developed in 1234. In Europe, sporadic evidence that the typographical principle, the idea of creating a text by reusing individual characters, was well understood and employed in pre-Gutenberg Europe had been cropping up since the 12th century and possibly before. The known examples range from Germany (Prüfening inscription) to England (letter tiles) to Italy. However, the various techniques employed (imprinting, punching and assembling individual letters) did not have the refinement and efficiency needed to become widely accepted.</p>
        <p>Gutenberg greatly improved the process by treating typesetting and printing as two separate work steps. A goldsmith by profession, he created his type pieces from a lead-based alloy which suited printing purposes so well that it is still used today. The mass production of metal letters was achieved by his key invention of a special hand mould, the matrix. The Latin alphabet proved to be an enormous advantage in the process because, in contrast to logographic writing systems, it allowed the type-setter to represent any text with a theoretical minimum of only around two dozen different letters.</p>
        <p>Another factor conducive to printing arose from the book existing in the format of the codex, which had originated in the Roman period. Considered the most important advance in the history of the book prior to printing itself, the codex had completely replaced the ancient scroll at the onset of the Middle Ages (500 AD). The codex holds considerable practical advantages over the scroll format; it is more convenient to read (by turning pages), is more compact, less costly, and, in particular, unlike the scroll, both recto and verso could be used for writing − and printing.</p>
      )
    },
    {
      id: '3',
      title: 'Tim Berners-Lee creates the World Wide Web',
      tagline: 'The new system allows people to communicate worldwide',
      image: 'http://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/First_Web_Server.jpg/1600px-First_Web_Server.jpg',
      summary: 'In the 1980s, the work of Tim Berners-Lee in the United Kingdom, on the World Wide Web, theorised the fact that protocols link hypertext documents into a working system, marking the beginning the modern Internet.',
      free_content: "<p>The history of the Internet begins with the development of electronic computers in the 1950s. Initial concepts of packet networking originated in several computer science laboratories in the United States, Great Britain, and France. The US Department of Defense awarded contracts as early as the 1960s for packet network systems, including the development of the ARPANET (which would become the first network to use the Internet Protocol.)",
      paid_content: %(
        <img style="width: 44%; float: left; margin-right: 20px;" src="http://blog.iese.edu/baker/files/2014/06/976719_0ed45ca20d.jpg" />
        <p>The first message was sent over the ARPANET from computer science Professor Leonard Kleinrock's laboratory at University of California, Los Angeles (UCLA) to the second network node at Stanford Research Institute (SRI).</p>
        <p>Packet switching networks such as ARPANET, Mark I at NPL in the UK, CYCLADES, Merit Network, Tymnet, and Telenet, were developed in the late 1960s and early 1970s using a variety of communications protocols. Donald Davies was the first to put theory into practice by designing a packet-switched network at the National Physics Laboratory in the UK, the first of its kind in the world and the cornerstone for UK research for almost two decades. Following, ARPANET further led to the development of protocols for internetworking, in which multiple separate networks could be joined into a network of networks.</p>
        <blockquote>Since the mid-1990s, the Internet has had a revolutionary impact on culture and commerce, including the rise of near-instant communication by electronic mail</blockquote>
        <p>Access to the ARPANET was expanded in 1981 when the National Science Foundation (NSF) funded the Computer Science Network (CSNET). In 1982, the Internet protocol suite (TCP/IP) was introduced as the standard networking protocol on the ARPANET.</p>
        <p>In the early 1980s the NSF funded the establishment for national supercomputing centers at several universities, and provided interconnectivity in 1986 with the NSFNET project, which also created network access to the supercomputer sites in the United States from research and education organizations. Commercial Internet service providers (ISPs) began to emerge in the late 1980s. The ARPANET was decommissioned in 1990. Private connections to the Internet by commercial entities became widespread quickly, and the NSFNET was decommissioned in 1995, removing the last restrictions on the use of the Internet to carry commercial traffic.</p>
        <p>In the 1980s, the work of Tim Berners-Lee in the United Kingdom, on the World Wide Web, theorised the fact that protocols link hypertext documents into a working system, marking the beginning the modern Internet.</p>
        <p>Since the mid-1990s, the Internet has had a revolutionary impact on culture and commerce, including the rise of near-instant communication by electronic mail, instant messaging, voice over Internet Protocol (VoIP) telephone calls, two-way interactive video calls, and the World Wide Web with its discussion forums, blogs, social networking, and online shopping sites. The research and education community continues to develop and use advanced networks such as NSF's very high speed Backbone Network Service (vBNS), Internet2, and National LambdaRail.</p>
        <p>Increasing amounts of data are transmitted at higher and higher speeds over fiber optic networks operating at 1-Gbit/s, 10-Gbit/s, or more. The Internet's takeover of the global communication landscape was almost instant in historical terms: it only communicated 1% of the information flowing through two-way telecommunications networks in the year 1993, already 51% by 2000, and more than 97% of the telecommunicated information by 2007. Today the Internet continues to grow, driven by ever greater amounts of online information, commerce, entertainment, and social networking.</p>
      )
    },
    {
      id: '4',
      premium: true,
      title: 'A thin, plant-based material for writing, called "paper" appears in China',
      tagline: 'The innovation is thinner and better than the papyrus',
      image: 'http://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Paperbook%2B256.jpg/934px-Paperbook%2B256.jpg',

      summary: "Paper was invented in ancient China during the Han dynasty (206 BC – 220 AD) and spread slowly to the west via the Silk Road. Papermaking and manufacturing in Europe was started by Muslims living on the Iberian Peninsula, (today's Portugal and Spain) and Sicily in the 10th century, and slowly spread to Italy and Southern France reaching Germany by 1400.",
      free_content: %(
        <p>Paper was invented in ancient China during the Han dynasty (206 BC – 220 AD) and spread slowly to the west via the Silk Road. Papermaking and manufacturing in Europe was started by Muslims living on the Iberian Peninsula, (today's Portugal and Spain) and Sicily in the 10th century, and slowly spread to Italy and Southern France reaching Germany by 1400. Earlier, other paper-like materials were in use including papyrus, parchment, palm leaves and vellum, but all of these were derived from raw materials which were expensive or in limited supply, or required extensive hand-processing to produce a satisfactory finish. Paper, being made from wood or rags, could be produced anywhere, and once large scale production techniques had been developed it could be manufactured in almost any quantity at moderate cost.</p>
      ),
      paid_content: %(
        <img style="width: 44%; float: left; margin-right: 20px;" src="http://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Jingangjing.jpg/1599px-Jingangjing.jpg" />
        <p>In medieval Europe, the hitherto handcraft of papermaking was mechanized by the use of waterpower, the first water papermill in the Iberian Peninsula having been built in the Portuguese city of Leiria in 1411, and other processes. The rapid expansion of European paper production was truly enhanced by the invention of the printing press and the beginning of the Printing Revolution in the 15th century.</p>
        <blockquote>Papermaking and manufacturing in Europe was started by Muslims living on the Iberian Peninsula, (today's Portugal and Spain) and Sicily in the 10th century</blockquote>
        <p>The word "paper" is etymologically derived from papyros, Ancient Greek for the Cyperus papyrus plant. Papyrus is a thick, paper-like material produced from the pith of the Cyperus papyrus plant which was used in ancient Egypt and other Mediterranean cultures for writing long before the making of paper in China. Papyrus however are plants dried and woven, while paper is manufactured from fibers whose properties have been changed by maceration or disintegration.</p>
        <p>Papermaking has traditionally been traced to China when Cai Lun, an official attached to the Imperial court during the Han Dynasty (202 BC-AD 220), created a sheet of paper using mulberry and other bast fibres along with fishnets, old rags, and hemp waste, though the earliest piece of paper found, at Fangmatan in Gansu province inscribed with a map, dates from 179-41 BC.Papermaking is made in Kashgar.</p>
        <p>During the Shang (1600–1050 BC) and Zhou (1050-256 BC) dynasties of ancient China, documents were ordinarily written on bone or bamboo (on tablets or on bamboo strips sewn and rolled together into scrolls), making them very heavy, awkward, and hard to transport. The light material of silk was sometimes used as a recording medium, but was normally too expensive to consider.</p>
        <p>The Han dynasty Chinese court official Cai Lun (ca. 50–121) is widely regarded as the inventor of the modern method of papermaking (inspired by wasps and bees) from rags and other plant fibers in 105. However, the discovery of specimens bearing written Chinese characters in 2006 at Fangmatan in north-east China's Gansu Province suggest that paper was in use by the ancient Chinese military more than 100 years before Cai, in 8 BC, and possibly much earlier as the map fragment found at the Fangmatan tomb site dates from the early 2nd century BC.[citation needed] It therefore would appear that "Cai Lun's contribution was to improve this skill systematically and scientifically, fix a recipe for papermaking".</p>
      )
    }
  ]

  def self.all
    ARTICLES.map{|article| Article.new(article) }
  end

  def self.find id
    all.find{ |article| article.id == id }
  end

  attr_reader :id, :premium, :title, :tagline, :image, :summary, :free_content, :paid_content
  def initialize(id:, premium: false, title:, tagline: , image:, summary:, free_content:, paid_content:)
    @id = id
    @premium = premium
    @title = title
    @tagline = tagline
    @image = image
    @summary = summary
    @free_content = free_content
    @paid_content = paid_content
  end

end
